name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

permissions:
  id-token: write       # Allows requesting an OIDC token for authentication
  contents: read        # Allows reading repository contents
  pages: write          # Allows publishing to GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build your static site (use appropriate build commands for your setup)
      - name: Build site
        run: |
          # Example: Jekyll build (for Jekyll-based sites)
          # If you use another static site generator, update this command
          bundle install
          bundle exec jekyll build -d build

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build  # Path to your built site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write        # Allows publishing to GitHub Pages
      id-token: write     # Allows requesting an OIDC token
    steps:
      - name: Deploy to GitHub Pages
        id: pages
        uses: actions/deploy-pages@v1
